# Generated by Django 3.2.9 on 2021-12-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_alter_user_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='std',
            field=models.CharField(default='Not Assigned', max_length=20),
        ),
    ]
